add: BearerAuthentication middleware
chand1012/openai-cf-workers-ai pull request #6
Opened 2024-04-10 10:50 UTC by devcxl

Adding the `BearerAuthentication` middleware enhances the security of the interface.

2024-04-10 14:22 UTC, chand1012 requested changes
I think overall these are good changes, however there are two small tweaks that I would make. Also thanks for the refactor of the endpoints, looks much cleaner now!

2024-04-10 14:22 UTC, chand1012 commented on index.js
> +const bearerAuthentication = (request, env) => {
I think this is a great change, however I think we should have the option to leave the `ACCESS_TOKEN` blank and to then ignore this middleware if and only if the token is omitted from the config.

2024-04-10 14:22 UTC, chand1012 commented on index.js
> +const router = Router({ base: '/v1' });
The base should be configurable via environment variable and the default should be blank, as in no added base URL.

2024-04-11 07:53 UTC, devcxl commented
I think it's necessary to enforce the addition of ACCESS_TOKEN to ensure the security of the interface. As for the suggestion to control the setting of the base using environment variables, it's indeed a good idea.

2024-04-11 07:57 UTC, devcxl commented
However, how to pass the environment variables to the base is a problem.

2024-04-11 14:49 UTC, chand1012 commented
That's fine then, could you modify the README to add instructions about changing the ACCESS_TOKEN so that people don't get confused when they get rejected by their instance? Thanks.

2024-04-11 14:50 UTC, chand1012 requested changes
Once instructions are added I'll merge.

2024-04-11 14:50 UTC, chand1012 commented on wrangler.toml
> +ACCESS_TOKEN = "sk-1234567890ASDFGHJKLQWERTYUIOP" # You can set any string value."
Need instructions about this in the README.

2024-04-11 16:14 UTC, devcxl commented
Okay, I'll update the README file later.

2024-04-11 16:30 UTC, devcxl commented
Done

2024-04-11 17:12 UTC, chand1012 approved these changes

2024-04-11 17:12 UTC, merged

2024-04-11 17:13 UTC, chand1012 commented
Thank you for your help!